print("Content-Type: text/html\r")
print("\r")
print("<html>")
print("<head><title>CGI Test - Python</title></head>")
print("<body>")
print("<h1>CGI Python Script Works!</h1>")
print("<p>This is a test CGI script written in Python.</p>")
print("</body>")
print("</html>")